
In JavaScript, a promise is a good way to handle **asynchronous** operations. It is used to find out if the asynchronous operation is successfully completed or not.

A promise may have one of three states.

- Pending
- Fulfilled
- Rejected

A promise starts in a pending state. That means the process is not complete. If the operation is successful, the process ends in a fulfilled state. And, if an error occurs, the process ends in a rejected state.

For example, when you request data from the server by using a promise, it will be in a pending state. When the data arrives successfully, it will be in a fulfilled state. If an error occurs, then it will be in a rejected state.


The `Promise()` constructor takes a function as an argument. The function also accepts two functions `resolve()` and `reject()`.

If the promise returns successfully, the `resolve()` function is called. And, if an error occurs, the `reject()` function is called.

```js
let promise = new Promise(function(resolve, reject){
     //do something
});
```


```js
const count = true;  
  
let countValue = new Promise(function (resolve, reject) {  
    if (count) {  
        resolve("There is a count value.");  
    } else {  
        reject("There is no count value");  
    }  
});  
  
console.log(countValue);
```


In the above program, a `Promise` object is created that takes two functions: `resolve()` and `reject()`. `resolve()` is used if the process is successful and `reject()` is used when an error occurs in the promise.

The promise is resolved if the value of count is true.

![[Pasted image 20231012175114.png]]


### then() and catch()

The `then()` method is used with the callback when the promise is successfully fulfilled or resolved.

The syntax of `then()` method is:

```js
promiseObject.then(onFulfilled, onRejected);
```

The `catch()` method is used with the callback when the promise is rejected or if an error occurs.


```js
// returns a promise
let countValue = new Promise(function (resolve, reject) {
   reject('Promise rejected'); 
});

// executes when promise is resolved successfully
countValue.then(
    function successValue(result) {
        console.log(result);
    },
 )

// executes if there is an error
.catch(
    function errorValue(result) {
        console.log(result);
    }
);
```

